import { Inter } from "next/font/google";
import Header from "./_components/Header";
import "./globals.css";
import Footer from "./_components/Footer";
import { Toaster } from "sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="md:px-20">
          <Header/>
          {children} 
          <Toaster/> 
        </div>
        <Footer/> 
      </body>
    </html>
  );
}
